theme: jekyll-theme-modernist
title: Immaculate Conception and NCSSM
description: Information on how interested NCSSM students can attend Mass and other events at Immaculate Conceptions Catholic Church
