theme: jekyll-theme-modernist
title: [Immaculate Conception and NCSSM]
description: [Information on how ingterested NCSSM students can attend Mass and events are Immaculate Conceptions Catholic Church]
